// Generated by tools/generate-app-content.ts. Do not edit by hand.
(function () {
  window.WEST_LAKE_CONTENT = {
  "siteNavigation": [
    {
      "id": "map",
      "label": "入画",
      "href": "/map"
    },
    {
      "id": "scroll",
      "label": "游湖",
      "href": "/scroll"
    },
    {
      "id": "notes",
      "label": "拾遗",
      "href": "/notes"
    },
    {
      "id": "inquiry",
      "label": "问湖",
      "href": "/inquiry"
    }
  ],
  "scrollSegments": [
    {
      "id": "sisheng-yanxiang-guan",
      "title": "孤山四圣延祥观",
      "src": "./assets/scroll/north-bank/孤山四圣延祥观.jpg",
      "image": "孤山四圣延祥观.jpg",
      "width": 9449,
      "height": 2480
    },
    {
      "id": "geling-pingzhang-di",
      "title": "葛岭寺观平章第",
      "src": "./assets/scroll/north-bank/葛岭寺观平章第.jpg",
      "image": "葛岭寺观平章第.jpg",
      "width": 9449,
      "height": 2480,
      "cropLeft": 740,
      "aliases": [
        "jiasidao-ci-di"
      ]
    },
    {
      "id": "volume-dashifo-yuan",
      "title": "巨石山下大石佛",
      "src": "./assets/scroll/north-bank/巨石山下大石佛.jpg",
      "image": "巨石山下大石佛.jpg",
      "width": 9449,
      "height": 2480,
      "cropLeft": 740
    }
  ],
  "scrollPanoramaNodes": [
    {
      "id": "xicun-dukou",
      "title": "西村渡口",
      "category": "渡口",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.012485186288011315,
        "y": 0.645
      },
      "subtitle": "XI · CUN · DU · KOU",
      "summary": "位于西湖西岸西村临湖地带，是南宋西湖北线环湖核心水路节点，衔接水上游船航线与岸上游路，配套西村酒楼形成游宴交通枢纽。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.006330516991104328,
        "y": 0.56,
        "width": 0.012309338593813975,
        "height": 0.17
      },
      "segmentId": "sisheng-yanxiang-guan",
      "card": {
        "markerLabel": "西村渡口",
        "pinyin": "XI · CUN · DU · KOU",
        "status": "南宋 · 西湖渡口",
        "intro": [
          "南宋西湖北岸",
          "西村临湖地带",
          "水陆转换节点"
        ],
        "seal": "渡",
        "sections": [
          [
            "节点简介",
            "位于西湖西岸西村临湖地带，是南宋西湖北线环湖核心水路节点，衔接水上游船航线与岸上游路，配套西村酒楼形成游宴交通枢纽。"
          ],
          [
            "南宋建制",
            "南宋时称西村埠（俗称西村渡口），为官方规制的环湖固定渡口，设石砌埠头与候船廊榭，承担游船停泊、士庶登岸、短途摆渡功能，是西线环湖游赏路线的水陆转换核心节点。"
          ],
          [
            "今日坐标",
            "遗址约在今西湖西岸北山街西段临湖区域，宋代原埠头基址与设施已完全湮灭，现存湖岸为后世历次整治后的格局。"
          ],
          [
            "史迹价值",
            "是南宋西湖“水上游赏 + 岸上游览”联动体系的典型见证，直观反映了南宋西湖水上交通网络的成熟度与环湖游憩经济的繁盛面貌。"
          ]
        ]
      },
      "markerLabel": "西村渡口"
    },
    {
      "id": "xicun-jiulou",
      "title": "西村酒楼",
      "category": "市井",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.04906150668105855,
        "y": 0.455
      },
      "subtitle": "XI · CUN · JIU · LOU",
      "summary": "位于西湖西岸西村临湖地带，为南宋时期知名临湖酒楼，是环湖市井商业与游宴文化的核心载体。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.04290683738415156,
        "y": 0.37,
        "width": 0.012309338593813975,
        "height": 0.17
      },
      "segmentId": "sisheng-yanxiang-guan",
      "card": {
        "markerLabel": "西村酒楼",
        "pinyin": "XI · CUN · JIU · LOU",
        "status": "南宋 · 临湖酒楼",
        "intro": [
          "南宋西湖北岸",
          "西村临湖地带",
          "游宴商业节点"
        ],
        "seal": "酒",
        "sections": [
          [
            "节点简介",
            "位于西湖西岸西村临湖地带，为南宋时期知名临湖酒楼，是环湖市井商业与游宴文化的核心载体。"
          ],
          [
            "南宋建制",
            "南宋时称西村酒楼，为临湖大型商业酒楼，临湖设观景席座，兼具餐饮、宴饮与休闲功能，服务于游湖士庶与文人雅士。"
          ],
          [
            "今日坐标",
            "遗址约在今西湖西岸北山街西段区域，原建筑已完全湮灭，无地表遗存。"
          ],
          [
            "史迹价值",
            "是南宋西湖游宴文化与环湖商业业态的典型见证，直观反映了南宋临安市民休闲经济与西湖旅游文化的繁盛面貌。"
          ]
        ]
      },
      "markerLabel": "西村酒楼"
    },
    {
      "id": "baoshu-ta-chongshou-yuan",
      "title": "保俶塔与崇寿院",
      "category": "寺塔",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.08088993933077754,
        "y": 0.155
      },
      "subtitle": "BAO · CHU · TA",
      "summary": "坐落于宝石山巅，保俶塔为吴越始建的佛塔，山麓配套崇寿院寺院，是南宋西湖北岸最醒目的视觉地标。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.07385603156288384,
        "y": 0.065,
        "width": 0.014067815535787398,
        "height": 0.18
      },
      "segmentId": "sisheng-yanxiang-guan",
      "card": {
        "markerLabel": "保俶塔",
        "pinyin": "BAO · CHU · TA",
        "status": "南宋 · 西湖寺塔",
        "intro": [
          "南宋西湖北岸",
          "宝石山巅",
          "视觉地标"
        ],
        "seal": "塔",
        "sections": [
          [
            "节点简介",
            "坐落于宝石山巅，保俶塔为吴越始建的佛塔，山麓配套崇寿院寺院，是南宋西湖北岸最醒目的视觉地标。"
          ],
          [
            "南宋建制",
            "南宋时塔称保俶塔，为八级砖木结构佛塔；附属崇寿院为北山正规禅院，塔院一体，是西湖环湖梵刹体系的制高点节点。"
          ],
          [
            "今日坐标",
            "保俶塔现存（历代屡经修缮），为西湖核心地标；崇寿院建筑已湮灭，遗址分布于宝石山巅塔基周边。"
          ],
          [
            "史迹价值",
            "是五代至南宋西湖佛教建筑的核心代表，其塔院共生的格局见证了西湖山地佛教景观的营造传统。"
          ]
        ]
      },
      "markerLabel": "保俶塔"
    },
    {
      "id": "sisheng-yanxiang-guan",
      "title": "四圣延祥观",
      "category": "宫观",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.17408921725536905,
        "y": 0.215
      },
      "subtitle": "SI · SHENG · YAN · XIANG · GUAN",
      "summary": "位于孤山南麓临湖地带，为南宋皇家敕建道教宫观，是孤山区域规格最高的道教建筑，兼具祭祀与游赏功能。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.16529683254550193,
        "y": 0.12,
        "width": 0.017584769419734247,
        "height": 0.19
      },
      "segmentId": "sisheng-yanxiang-guan",
      "card": {
        "markerLabel": "四圣延祥观",
        "pinyin": "SI · SHENG · YAN · XIANG · GUAN",
        "status": "南宋 · 皇家宫观",
        "intro": [
          "南宋西湖北岸",
          "孤山南麓",
          "皇家道教建筑"
        ],
        "seal": "观",
        "sections": [
          [
            "节点简介",
            "位于孤山南麓临湖地带，为南宋皇家敕建道教宫观，是孤山区域规格最高的道教建筑，兼具祭祀与游赏功能。"
          ],
          [
            "南宋建制",
            "南宋咸淳年间为四圣延祥观，属御前宫观，主祀天蓬、天猷、翊圣、真武四圣真君，殿宇巍峨，内有六一泉等名胜，由内侍管理，为皇室游湖驻跸之所。"
          ],
          [
            "今日坐标",
            "遗址位于今西湖孤山公园南麓，原宫观建筑已完全湮灭，六一泉等附属遗迹尚存。"
          ],
          [
            "史迹价值",
            "是南宋皇家道教与山水园林结合的典型代表，见证了南宋道教文化与孤山景观体系的融合发展。"
          ]
        ]
      },
      "markerLabel": "四圣延祥观"
    },
    {
      "id": "xi-taiyi-gong",
      "title": "西太乙宫",
      "category": "宫观",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.2919071723675885,
        "y": 0.35
      },
      "subtitle": "XI · TAI · YI · GONG",
      "summary": "位于钱塘门外临湖地带，为南宋皇家敕建道教宫观，是杭州规格最高的国家级道教祭祀建筑之一。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.2848732645996948,
        "y": 0.26,
        "width": 0.014067815535787398,
        "height": 0.18
      },
      "segmentId": "sisheng-yanxiang-guan",
      "card": {
        "markerLabel": "西太乙宫",
        "pinyin": "XI · TAI · YI · GONG",
        "status": "南宋 · 皇家宫观",
        "intro": [
          "南宋西湖北岸",
          "钱塘门外",
          "国家祭祀建筑"
        ],
        "seal": "宫",
        "sections": [
          [
            "节点简介",
            "位于钱塘门外临湖地带，为南宋皇家敕建道教宫观，是杭州规格最高的国家级道教祭祀建筑之一。"
          ],
          [
            "南宋建制",
            "南宋咸淳年间为西太乙宫，属御前皇家宫观，主祀太乙神，殿宇宏丽，规制比照皇家宫殿，由朝廷委派官员管理，承担国家祭祀功能。"
          ],
          [
            "今日坐标",
            "遗址约在今北山街东段靠近钱塘门区域，宋代原构建筑已完全湮灭，无地表遗存。"
          ],
          [
            "史迹价值",
            "是南宋皇家道教体系的核心建筑代表，见证了南宋国家祭祀制度与道教建筑的高等级营造规制。"
          ]
        ]
      },
      "markerLabel": "西太乙宫"
    },
    {
      "id": "chushi-qiao",
      "title": "处士桥",
      "category": "桥梁",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.3395618974950683,
        "y": 0.9199999999999999
      },
      "subtitle": "CHU · SHI · QIAO",
      "summary": "位于西湖西岸环湖地带，为南宋跨水石桥，因关联北宋处士林逋得名，是环湖交通与景观结合的典型节点。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.3334072281981613,
        "y": 0.835,
        "width": 0.012309338593813975,
        "height": 0.17
      },
      "segmentId": "sisheng-yanxiang-guan",
      "card": {
        "markerLabel": "处士桥",
        "pinyin": "CHU · SHI · QIAO",
        "status": "南宋 · 西湖桥梁",
        "intro": [
          "南宋西湖北岸",
          "孤山西北麓",
          "环湖交通节点"
        ],
        "seal": "桥",
        "sections": [
          [
            "节点简介",
            "位于西湖西岸环湖地带，为南宋跨水石桥，因关联北宋处士林逋得名，是环湖交通与景观结合的典型节点。"
          ],
          [
            "南宋建制",
            "南宋时称处士桥，为石砌拱桥，是西岸环湖游路的核心桥梁，连通南北寺观园林，为游湖士庶的必经之地。"
          ],
          [
            "今日坐标",
            "遗址约在今孤山西北麓环湖区域，原宋代石桥已不存，后世屡经改建，格局已发生变化。"
          ],
          [
            "史迹价值",
            "是南宋西湖环湖交通体系的实物见证，其命名承载了西湖隐逸文化记忆，是人文与景观结合的典型节点。"
          ]
        ]
      },
      "markerLabel": "处士桥"
    },
    {
      "id": "manao-si",
      "title": "玛瑙寺",
      "category": "寺院",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.5587331298619124,
        "y": 0.32499999999999996
      },
      "subtitle": "MA · NAO · SI",
      "summary": "位于宝石山西麓，五代始建，原名玛瑙宝胜院，因山产玛瑙石得名，南宋时为北山历史悠久的知名古刹。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.5516992220940187,
        "y": 0.235,
        "width": 0.014067815535787396,
        "height": 0.18
      },
      "segmentId": "geling-pingzhang-di",
      "card": {
        "markerLabel": "玛瑙寺",
        "pinyin": "MA · NAO · SI",
        "status": "南宋 · 西湖古刹",
        "intro": [
          "南宋西湖北岸",
          "宝石山西麓",
          "禅宗寺院"
        ],
        "seal": "寺",
        "sections": [
          [
            "节点简介",
            "位于宝石山西麓，五代始建，原名玛瑙宝胜院，因山产玛瑙石得名，南宋时为北山历史悠久的知名古刹。"
          ],
          [
            "南宋建制",
            "南宋时定名玛瑙宝胜院（俗称玛瑙寺），属禅宗寺院，殿宇依山错落排布，坐拥湖山之胜，规制完备，为北山核心梵刹之一。"
          ],
          [
            "今日坐标",
            "遗址位于今北山街玛瑙寺地块，尚存部分明清建筑与千年古樟等历史遗存，为杭州市文物保护点。"
          ],
          [
            "史迹价值",
            "是西湖北山少数基址沿革清晰、延续千年的古寺院，见证了五代至南宋西湖佛教建筑的发展脉络与营造技艺。"
          ]
        ]
      },
      "markerLabel": "玛瑙寺"
    },
    {
      "id": "houleyuan-jifang-yuyuan",
      "title": "后乐园",
      "category": "园林",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.5140678155357874,
        "y": 0.32499999999999996
      },
      "subtitle": "HOU · LE · YUAN",
      "summary": "位于葛岭山麓，为南宋权臣贾似道营建的私家园林，取“后天下之乐而乐”之意，是南宋后期西湖规模最大的权贵园林。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.5070339077678937,
        "y": 0.235,
        "width": 0.014067815535787396,
        "height": 0.18
      },
      "segmentId": "geling-pingzhang-di",
      "card": {
        "markerLabel": "后乐园",
        "pinyin": "HOU · LE · YUAN",
        "status": "南宋 · 权贵园林",
        "intro": [
          "南宋西湖北岸",
          "葛岭山麓",
          "私家园林"
        ],
        "seal": "园",
        "sections": [
          [
            "节点简介",
            "位于葛岭山麓，为南宋权臣贾似道营建的私家园林，取“后天下之乐而乐”之意，是南宋后期西湖规模最大的权贵园林。"
          ],
          [
            "南宋建制",
            "咸淳年间臻于鼎盛，依葛岭湖山之势构筑亭台楼阁、水榭池馆，引水造景，广植花木，兼具雅集、宴饮与休闲功能，代表南宋私家园林最高水准。"
          ],
          [
            "今日坐标",
            "遗址位于今葛岭一带临湖区域，原园林建筑已完全湮灭，部分山水基底与地形格局仍可寻迹。"
          ],
          [
            "史迹价值",
            "是南宋权贵园林的巅峰代表，集中体现了南宋西湖造园艺术的最高成就，也是南宋后期社会阶层与园林文化的缩影。"
          ]
        ]
      },
      "markerLabel": "后乐园"
    },
    {
      "id": "jiasidao-ci-di",
      "title": "贾似道赐第",
      "category": "宅第",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.5520509174824134,
        "y": 0.585
      },
      "subtitle": "JIA · SI · DAO · CI · DI",
      "summary": "位于葛岭东麓临湖地带，为南宋理宗赐予权臣贾似道的官邸，是南宋后期西湖西岸规格最高的权贵宅邸。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.5450170097145197,
        "y": 0.495,
        "width": 0.014067815535787396,
        "height": 0.18
      },
      "segmentId": "geling-pingzhang-di",
      "card": {
        "markerLabel": "贾似道赐第",
        "pinyin": "JIA · SI · DAO · CI · DI",
        "status": "南宋 · 权贵宅第",
        "intro": [
          "南宋西湖北岸",
          "葛岭东麓",
          "宅园合一"
        ],
        "seal": "第",
        "sections": [
          [
            "节点简介",
            "位于葛岭东麓临湖地带，为南宋理宗赐予权臣贾似道的官邸，是南宋后期西湖西岸规格最高的权贵宅邸。"
          ],
          [
            "南宋建制",
            "咸淳年间为贾似道“平章军国事”的行在宅邸，规制宏敞，兼具办公、居住与游赏功能，与西侧后乐园连为一体，形成宅园合一的格局。"
          ],
          [
            "今日坐标",
            "遗址位于今葛岭东段临湖区域，原宅邸建筑已完全湮灭，仅存少量基址与相关摩崖刻石遗迹。"
          ],
          [
            "史迹价值",
            "是南宋权臣政治与西湖宅园文化结合的典型代表，为研究南宋后期政治史、建筑史与园林史提供了重要线索。"
          ]
        ]
      },
      "markerLabel": "贾似道赐第"
    },
    {
      "id": "baoyun-si",
      "title": "宝云寺",
      "category": "寺院",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.6005848810808799,
        "y": 0.28
      },
      "subtitle": "BAO · YUN · SI",
      "summary": "位于西湖北山之阳，北宋始建，南宋时为环湖梵刹体系中的中型尼院，以环境清幽著称。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.5935509733129862,
        "y": 0.19,
        "width": 0.014067815535787396,
        "height": 0.18
      },
      "segmentId": "geling-pingzhang-di",
      "card": {
        "markerLabel": "宝云寺",
        "pinyin": "BAO · YUN · SI",
        "status": "南宋 · 西湖尼院",
        "intro": [
          "南宋西湖北岸",
          "北山之阳",
          "佛教尼院"
        ],
        "seal": "寺",
        "sections": [
          [
            "节点简介",
            "位于西湖北山之阳，北宋始建，南宋时为环湖梵刹体系中的中型尼院，以环境清幽著称。"
          ],
          [
            "南宋建制",
            "南宋时定名宝云院（俗称宝云寺），为比丘尼寺院，殿堂规整，依山临湖，是北山佛教景观带的组成部分。"
          ],
          [
            "今日坐标",
            "遗址约在今北山街沿线临湖区域，宋代原构建筑已完全湮灭，无地表遗存。"
          ],
          [
            "史迹价值",
            "是南宋西湖佛教体系中尼寺类建筑的代表，为研究南宋杭州佛教群体构成与寺院布局提供了历史参照。"
          ]
        ]
      },
      "markerLabel": "宝云寺"
    },
    {
      "id": "tang-zhaoxian-si-song-chanzong-yuan",
      "title": "唐招贤寺",
      "category": "寺院",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.4148897160084863,
        "y": 0.31
      },
      "subtitle": "TANG · ZHAO · XIAN · SI",
      "summary": "位于西湖北山临湖地带，始建于唐代，故名“唐招贤寺”，南宋时历经重修，是环湖少数肇始于唐的古刹。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.4078558082405926,
        "y": 0.22,
        "width": 0.014067815535787396,
        "height": 0.18
      },
      "segmentId": "geling-pingzhang-di",
      "card": {
        "markerLabel": "唐招贤寺",
        "pinyin": "TANG · ZHAO · XIAN · SI",
        "status": "南宋 · 西湖古刹",
        "intro": [
          "南宋西湖北岸",
          "北山临湖地带",
          "唐代古刹"
        ],
        "seal": "寺",
        "sections": [
          [
            "节点简介",
            "位于西湖北山临湖地带，始建于唐代，故名“唐招贤寺”，南宋时历经重修，是环湖少数肇始于唐的古刹。"
          ],
          [
            "南宋建制",
            "南宋咸淳年间定名招贤寺，俗称唐招贤寺，属佛教教院体系，殿堂齐备，寺内多古木碑刻，临湖而建，为香客巡礼与游人休憩之所。"
          ],
          [
            "今日坐标",
            "遗址约在今北山街西段临湖区域，宋代原构建筑已完全湮灭，具体基址待考古确认。"
          ],
          [
            "史迹价值",
            "是西湖佛教文化自唐至宋传承延续的重要见证，为研究杭州早期佛教传播与西湖景观演变提供了历史参照。"
          ]
        ]
      },
      "markerLabel": "唐招贤寺"
    },
    {
      "id": "yixiu-yuan",
      "title": "挹秀园",
      "category": "园林",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.7137199538467265,
        "y": 0.5599999999999999
      },
      "subtitle": "YI · XIU · YUAN",
      "summary": "位于西湖北山临湖地带，为南宋中期知名私家园林，因揽纳湖山秀色得名，是士人雅集游赏的重要场所。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.7066860460788328,
        "y": 0.47,
        "width": 0.014067815535787396,
        "height": 0.18
      },
      "segmentId": "volume-dashifo-yuan",
      "card": {
        "markerLabel": "挹秀园",
        "pinyin": "YI · XIU · YUAN",
        "status": "南宋 · 士人园林",
        "intro": [
          "南宋西湖北岸",
          "北山临湖地带",
          "士人园林"
        ],
        "seal": "园",
        "sections": [
          [
            "节点简介",
            "位于西湖北山临湖地带，为南宋中期知名私家园林，因揽纳湖山秀色得名，是士人雅集游赏的重要场所。"
          ],
          [
            "南宋建制",
            "南宋时称挹秀园，依湖山之势构筑亭台，临湖设观景台榭，可远眺南北两山，为北山园林带中士人园林的代表。"
          ],
          [
            "今日坐标",
            "遗址约在今北山街中段临湖区域，原园林建筑与山水格局已完全湮灭。"
          ],
          [
            "史迹价值",
            "代表了南宋西湖士人阶层的园林审美与造园理念，是南宋环湖私家园林兴盛局面的重要佐证。"
          ]
        ]
      },
      "markerLabel": "挹秀园"
    },
    {
      "id": "duobao-si",
      "title": "多宝寺",
      "category": "寺院",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.7559234004540887,
        "y": 0.198
      },
      "subtitle": "DUO · BAO · SI",
      "summary": "位于宝石山南麓临湖地带，五代始建，南宋时为西湖北山环湖梵刹序列中的重要寺院。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.748889492686195,
        "y": 0.108,
        "width": 0.014067815535787396,
        "height": 0.18
      },
      "segmentId": "volume-dashifo-yuan",
      "card": {
        "markerLabel": "多宝寺",
        "pinyin": "DUO · BAO · SI",
        "status": "南宋 · 西湖寺院",
        "intro": [
          "南宋西湖北岸",
          "宝石山南麓",
          "环湖梵刹"
        ],
        "seal": "寺",
        "sections": [
          [
            "节点简介",
            "位于宝石山南麓临湖地带，五代始建，南宋时为西湖北山环湖梵刹序列中的重要寺院。"
          ],
          [
            "南宋建制",
            "南宋时定名多宝寺，属佛教教院体系，殿堂齐备，临湖而建，与周边大石佛院、崇寿院共同构成北山佛教景观带。"
          ],
          [
            "今日坐标",
            "遗址约在今宝石山东南麓临湖区域，宋代原构建筑已完全湮灭，无明确地表遗存。"
          ],
          [
            "史迹价值",
            "是南宋西湖环湖寺院格局的重要组成节点，见证了五代至南宋北山佛教传播与寺院分布的历史脉络。"
          ]
        ]
      },
      "markerLabel": "多宝寺"
    },
    {
      "id": "zhiguo-yuan",
      "title": "智果院",
      "category": "寺院",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.6790129526928946,
        "y": 0.28800000000000003
      },
      "subtitle": "ZHI · GUO · YUAN",
      "summary": "位于宝石山西麓，北宋始建，南宋时为北山知名禅院，以林泉清幽、智果泉名世，是文人与僧人交游的核心场所。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.6719790449250009,
        "y": 0.198,
        "width": 0.014067815535787396,
        "height": 0.18
      },
      "segmentId": "geling-pingzhang-di",
      "card": {
        "markerLabel": "智果院",
        "pinyin": "ZHI · GUO · YUAN",
        "status": "南宋 · 北山禅院",
        "intro": [
          "南宋西湖北岸",
          "宝石山西麓",
          "智果泉名胜"
        ],
        "seal": "院",
        "sections": [
          [
            "节点简介",
            "位于宝石山西麓，北宋始建，南宋时为北山知名禅院，以林泉清幽、智果泉名世，是文人与僧人交游的核心场所。"
          ],
          [
            "南宋建制",
            "南宋时定名智果院，属禅宗寺院，殿宇依山而建，院内有名泉智果泉，兼具修行与游赏功能，为北山禅院代表。"
          ],
          [
            "今日坐标",
            "遗址位于今宝石山西侧，宋代建筑已湮灭，智果泉泉眼遗迹尚存，可寻历史脉络。"
          ],
          [
            "史迹价值",
            "是两宋西湖“禅院园林化”特征的典型代表，见证了宋代文人与禅僧交游文化的发展与兴盛。"
          ]
        ]
      },
      "markerLabel": "智果院"
    },
    {
      "id": "shuiyue-yuan",
      "title": "水月园",
      "category": "园林",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.7777285145345592,
        "y": 0.43999999999999995
      },
      "subtitle": "SHUI · YUE · YUAN",
      "summary": "位于钱塘门外临湖地带，为南宋北山知名园林，以临湖赏月的水景营造为核心特色，是南宋西湖名园的代表之一。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.7706946067666655,
        "y": 0.35,
        "width": 0.014067815535787396,
        "height": 0.18
      },
      "segmentId": "volume-dashifo-yuan",
      "card": {
        "markerLabel": "水月园",
        "pinyin": "SHUI · YUE · YUAN",
        "status": "南宋 · 临湖御园",
        "intro": [
          "南宋西湖北岸",
          "钱塘门外",
          "水景园林"
        ],
        "seal": "园",
        "sections": [
          [
            "节点简介",
            "位于钱塘门外临湖地带，为南宋北山知名园林，以临湖赏月的水景营造为核心特色，是南宋西湖名园的代表之一。"
          ],
          [
            "南宋建制",
            "南宋时初为权臣杨沂中别业，后收归官营，称水月御园，为皇室与朝臣游赏宴饮之所，临湖构亭榭，是北山园林带的核心节点。"
          ],
          [
            "今日坐标",
            "遗址约在今北山街东段临湖区域，原园林建筑与格局已完全湮灭，无地表宋代遗存。"
          ],
          [
            "史迹价值",
            "是南宋私家园林向官营御园转变的典型样本，代表了南宋西湖临湖造园的艺术水准与皇家游赏文化特征。"
          ]
        ]
      },
      "markerLabel": "水月园"
    },
    {
      "id": "shisanjianlou",
      "title": "十三间楼",
      "category": "建筑",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.8628387985260729,
        "y": 0.25
      },
      "subtitle": "SHI · SAN · JIAN · LOU",
      "summary": "位于大石佛院后山山巅，为吴越始建的连廊式楼阁，两宋时期是文人登高览胜、雅集题咏的核心胜地。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.8558048907581792,
        "y": 0.16,
        "width": 0.014067815535787396,
        "height": 0.18
      },
      "segmentId": "volume-dashifo-yuan",
      "card": {
        "markerLabel": "十三间楼",
        "pinyin": "SHI · SAN · JIAN · LOU",
        "status": "南宋 · 登览楼阁",
        "intro": [
          "南宋西湖北岸",
          "大石佛院后山",
          "文人雅集地"
        ],
        "seal": "楼",
        "sections": [
          [
            "节点简介",
            "位于大石佛院后山山巅，为吴越始建的连廊式楼阁，两宋时期是文人登高览胜、雅集题咏的核心胜地。"
          ],
          [
            "南宋建制",
            "南宋时称十三间楼，为北山标志性观景建筑，兼具宴饮、题咏、游赏功能，是临安士人西湖交游的高频打卡地。"
          ],
          [
            "今日坐标",
            "宋代原构建筑已完全湮灭，遗址位于今宝石山南麓大石佛院后山区域，地表无宋代建筑遗存。"
          ],
          [
            "史迹价值",
            "见证了两宋西湖文人游赏文化的兴盛，是研究南宋士人交游传统与西湖雅集文化的重要史迹节点。"
          ]
        ]
      },
      "markerLabel": "十三间楼"
    },
    {
      "id": "dashifo-yuan",
      "title": "大石佛院（兜率寺）",
      "category": "寺院",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.8874574757137008,
        "y": 0.33999999999999997
      },
      "subtitle": "DA · SHI · FO · YUAN",
      "summary": "坐落于宝石山东南麓，依托天然秦皇缆船石雕凿金装半身石佛，又称“大佛头”，是南宋临安城北最负盛名的梵刹之一。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.8786650910038337,
        "y": 0.245,
        "width": 0.017584769419734247,
        "height": 0.19
      },
      "segmentId": "volume-dashifo-yuan",
      "card": {
        "markerLabel": "大石佛院",
        "pinyin": "DA · SHI · FO · YUAN",
        "status": "南宋 · 西湖梵刹",
        "intro": [
          "南宋西湖北岸",
          "宝石山东南麓",
          "摩崖造像寺院"
        ],
        "seal": "佛",
        "sections": [
          [
            "节点简介",
            "坐落于宝石山东南麓，依托天然秦皇缆船石雕凿金装半身石佛，又称“大佛头”，是南宋临安城北最负盛名的梵刹之一。"
          ],
          [
            "南宋建制",
            "南宋时官方定名兜率寺，别名大石佛院，形成“石佛与梵宫共生”的独特格局，主殿为最高等级重檐歇山顶，覆盖金装摩崖石佛。"
          ],
          [
            "今日坐标",
            "遗存位于杭州市北山街 25 号院内，石佛残迹与清代弥勒院建筑尚存，为杭州重要历史史迹。"
          ],
          [
            "史迹价值",
            "是西湖规模最大的古代摩崖造像之一，为研究南宋佛教艺术、西湖营造格局提供了核心实物佐证。"
          ]
        ]
      },
      "markerLabel": "大石佛院"
    },
    {
      "id": "duanqiao",
      "title": "断桥",
      "category": "桥梁",
      "sourceStatus": "较可信",
      "position": {
        "x": 0.9577965533926378,
        "y": 0.6699999999999999
      },
      "subtitle": "DUAN · QIAO",
      "summary": "位于白堤东端，跨西湖内湖与外湖，是南宋西湖北岸连通临安城区的核心景观桥梁，也是白堤的标志性起点。",
      "source": "content/scroll-nodes.json",
      "noteId": "note-north-bank",
      "hit": {
        "x": 0.9507626456247441,
        "y": 0.58,
        "width": 0.014067815535787396,
        "height": 0.18
      },
      "segmentId": "volume-dashifo-yuan",
      "card": {
        "markerLabel": "断桥",
        "pinyin": "DUAN · QIAO",
        "status": "南宋 · 西湖堤桥",
        "intro": [
          "南宋西湖北岸",
          "白堤东端",
          "核心景观桥梁"
        ],
        "seal": "桥",
        "sections": [
          [
            "节点简介",
            "位于白堤东端，跨西湖内湖与外湖，是南宋西湖北岸连通临安城区的核心景观桥梁，也是白堤的标志性起点。"
          ],
          [
            "南宋建制",
            "南宋时正式称断桥，为石墩木梁式平桥，桥畔建有亭阁，是钱塘门入城游湖的第一节点，属西湖核心地标景观。"
          ],
          [
            "今日坐标",
            "位于今西湖白堤东端，现存桥梁为后世改建，格局与南宋略有差异，为西湖核心标志性景观。"
          ],
          [
            "史迹价值",
            "是南宋西湖“一湖三堤”景观格局的核心组成节点，见证了八百年来西湖堤桥体系的沿革，承载着西湖文化的核心记忆。"
          ]
        ]
      },
      "markerLabel": "断桥"
    }
  ],
  "coldKnowledgeSections": [
    {
      "id": "hushan-sui-shi",
      "title": "湖山岁时",
      "subtitle": "节气习俗",
      "description": "从岁时令节进入南宋临安的湖山风物。",
      "packDownload": "./assets/downloads/西湖繁胜冷识集-湖山岁时-24张.zip",
      "cards": [
        {
          "type": "image",
          "title": "湖山岁时 01",
          "label": "01",
          "src": "./assets/cold-knowledge/hushan-sui-shi/1.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第01张冷识卡片",
          "downloadName": "湖山岁时-01.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 02",
          "label": "02",
          "src": "./assets/cold-knowledge/hushan-sui-shi/2.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第02张冷识卡片",
          "downloadName": "湖山岁时-02.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 03",
          "label": "03",
          "src": "./assets/cold-knowledge/hushan-sui-shi/3.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第03张冷识卡片",
          "downloadName": "湖山岁时-03.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 04",
          "label": "04",
          "src": "./assets/cold-knowledge/hushan-sui-shi/4.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第04张冷识卡片",
          "downloadName": "湖山岁时-04.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 05",
          "label": "05",
          "src": "./assets/cold-knowledge/hushan-sui-shi/5.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第05张冷识卡片",
          "downloadName": "湖山岁时-05.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 06",
          "label": "06",
          "src": "./assets/cold-knowledge/hushan-sui-shi/6.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第06张冷识卡片",
          "downloadName": "湖山岁时-06.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 07",
          "label": "07",
          "src": "./assets/cold-knowledge/hushan-sui-shi/7.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第07张冷识卡片",
          "downloadName": "湖山岁时-07.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 08",
          "label": "08",
          "src": "./assets/cold-knowledge/hushan-sui-shi/8.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第08张冷识卡片",
          "downloadName": "湖山岁时-08.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 09",
          "label": "09",
          "src": "./assets/cold-knowledge/hushan-sui-shi/9.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第09张冷识卡片",
          "downloadName": "湖山岁时-09.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 10",
          "label": "10",
          "src": "./assets/cold-knowledge/hushan-sui-shi/10.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第10张冷识卡片",
          "downloadName": "湖山岁时-10.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 11",
          "label": "11",
          "src": "./assets/cold-knowledge/hushan-sui-shi/11.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第11张冷识卡片",
          "downloadName": "湖山岁时-11.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 12",
          "label": "12",
          "src": "./assets/cold-knowledge/hushan-sui-shi/12.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第12张冷识卡片",
          "downloadName": "湖山岁时-12.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 13",
          "label": "13",
          "src": "./assets/cold-knowledge/hushan-sui-shi/13.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第13张冷识卡片",
          "downloadName": "湖山岁时-13.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 14",
          "label": "14",
          "src": "./assets/cold-knowledge/hushan-sui-shi/14.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第14张冷识卡片",
          "downloadName": "湖山岁时-14.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 15",
          "label": "15",
          "src": "./assets/cold-knowledge/hushan-sui-shi/15.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第15张冷识卡片",
          "downloadName": "湖山岁时-15.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 16",
          "label": "16",
          "src": "./assets/cold-knowledge/hushan-sui-shi/16.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第16张冷识卡片",
          "downloadName": "湖山岁时-16.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 17",
          "label": "17",
          "src": "./assets/cold-knowledge/hushan-sui-shi/17.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第17张冷识卡片",
          "downloadName": "湖山岁时-17.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 18",
          "label": "18",
          "src": "./assets/cold-knowledge/hushan-sui-shi/18.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第18张冷识卡片",
          "downloadName": "湖山岁时-18.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 19",
          "label": "19",
          "src": "./assets/cold-knowledge/hushan-sui-shi/19.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第19张冷识卡片",
          "downloadName": "湖山岁时-19.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 20",
          "label": "20",
          "src": "./assets/cold-knowledge/hushan-sui-shi/20.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第20张冷识卡片",
          "downloadName": "湖山岁时-20.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 21",
          "label": "21",
          "src": "./assets/cold-knowledge/hushan-sui-shi/21.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第21张冷识卡片",
          "downloadName": "湖山岁时-21.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 22",
          "label": "22",
          "src": "./assets/cold-knowledge/hushan-sui-shi/22.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第22张冷识卡片",
          "downloadName": "湖山岁时-22.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 23",
          "label": "23",
          "src": "./assets/cold-knowledge/hushan-sui-shi/23.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第23张冷识卡片",
          "downloadName": "湖山岁时-23.png"
        },
        {
          "type": "image",
          "title": "湖山岁时 24",
          "label": "24",
          "src": "./assets/cold-knowledge/hushan-sui-shi/24.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖山岁时第24张冷识卡片",
          "downloadName": "湖山岁时-24.png"
        }
      ]
    },
    {
      "id": "hushang-yanhuo",
      "title": "湖上烟火",
      "subtitle": "市井生活",
      "description": "从茶酒食饮、舟船游宴到摊贩市声与节庆灯火，照见湖岸日常的热闹生息。",
      "packDownload": "./assets/downloads/西湖繁胜冷识集-湖上烟火-12张.zip",
      "cards": [
        {
          "type": "image",
          "title": "湖上烟火 01",
          "label": "01",
          "src": "./assets/cold-knowledge/hushang-yanhuo/1.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖上烟火第01张冷识卡片",
          "downloadName": "湖上烟火-01.png"
        },
        {
          "type": "image",
          "title": "湖上烟火 02",
          "label": "02",
          "src": "./assets/cold-knowledge/hushang-yanhuo/2.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖上烟火第02张冷识卡片",
          "downloadName": "湖上烟火-02.png"
        },
        {
          "type": "image",
          "title": "湖上烟火 03",
          "label": "03",
          "src": "./assets/cold-knowledge/hushang-yanhuo/3.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖上烟火第03张冷识卡片",
          "downloadName": "湖上烟火-03.png"
        },
        {
          "type": "image",
          "title": "湖上烟火 04",
          "label": "04",
          "src": "./assets/cold-knowledge/hushang-yanhuo/4.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖上烟火第04张冷识卡片",
          "downloadName": "湖上烟火-04.png"
        },
        {
          "type": "image",
          "title": "湖上烟火 05",
          "label": "05",
          "src": "./assets/cold-knowledge/hushang-yanhuo/5.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖上烟火第05张冷识卡片",
          "downloadName": "湖上烟火-05.png"
        },
        {
          "type": "image",
          "title": "湖上烟火 06",
          "label": "06",
          "src": "./assets/cold-knowledge/hushang-yanhuo/6.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖上烟火第06张冷识卡片",
          "downloadName": "湖上烟火-06.png"
        },
        {
          "type": "image",
          "title": "湖上烟火 07",
          "label": "07",
          "src": "./assets/cold-knowledge/hushang-yanhuo/7.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖上烟火第07张冷识卡片",
          "downloadName": "湖上烟火-07.png"
        },
        {
          "type": "image",
          "title": "湖上烟火 08",
          "label": "08",
          "src": "./assets/cold-knowledge/hushang-yanhuo/8.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖上烟火第08张冷识卡片",
          "downloadName": "湖上烟火-08.png"
        },
        {
          "type": "image",
          "title": "湖上烟火 09",
          "label": "09",
          "src": "./assets/cold-knowledge/hushang-yanhuo/9.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖上烟火第09张冷识卡片",
          "downloadName": "湖上烟火-09.png"
        },
        {
          "type": "image",
          "title": "湖上烟火 10",
          "label": "10",
          "src": "./assets/cold-knowledge/hushang-yanhuo/10.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖上烟火第10张冷识卡片",
          "downloadName": "湖上烟火-10.png"
        },
        {
          "type": "image",
          "title": "湖上烟火 11",
          "label": "11",
          "src": "./assets/cold-knowledge/hushang-yanhuo/11.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖上烟火第11张冷识卡片",
          "downloadName": "湖上烟火-11.png"
        },
        {
          "type": "image",
          "title": "湖上烟火 12",
          "label": "12",
          "src": "./assets/cold-knowledge/hushang-yanhuo/12.png",
          "width": 1086,
          "height": 1448,
          "alt": "湖上烟火第12张冷识卡片",
          "downloadName": "湖上烟火-12.png"
        }
      ]
    },
    {
      "id": "juanzhong-weishi",
      "title": "卷中微识",
      "subtitle": "画卷细节",
      "description": "从断桥桥构、大佛造像、沿湖茶担到船上食肆，读南宋西湖交通、信仰与市井消费的细节线索。",
      "packDownload": "./assets/downloads/西湖繁胜冷识集-卷中微识-4张.zip",
      "cards": [
        {
          "type": "image",
          "title": "断桥",
          "label": "01",
          "src": "./assets/cold-knowledge/juanzhong-weishi/01.png",
          "width": 1024,
          "height": 1536,
          "alt": "卷中微识第 1 张知识卡片：断桥，红栏白墩的宋代古桥。",
          "downloadName": "卷中微识-01.png"
        },
        {
          "type": "image",
          "title": "大佛头",
          "label": "02",
          "src": "./assets/cold-knowledge/juanzhong-weishi/02.png",
          "width": 1024,
          "height": 1536,
          "alt": "卷中微识第 2 张知识卡片：大佛头，秦皇缆船石变身记。",
          "downloadName": "卷中微识-02.png"
        },
        {
          "type": "image",
          "title": "茶司",
          "label": "03",
          "src": "./assets/cold-knowledge/juanzhong-weishi/03.png",
          "width": 1024,
          "height": 1536,
          "alt": "卷中微识第 3 张知识卡片：茶司，宋代的流动茶担。",
          "downloadName": "卷中微识-03.png"
        },
        {
          "type": "image",
          "title": "湖上外卖",
          "label": "04",
          "src": "./assets/cold-knowledge/juanzhong-weishi/04.png",
          "width": 1024,
          "height": 1536,
          "alt": "卷中微识第 4 张知识卡片：湖上外卖，南宋西湖的流动美食街。",
          "downloadName": "卷中微识-04.png"
        }
      ]
    }
  ],
  "mapPoints": [
    {
      "id": "map-duanqiao",
      "label": "断桥入口",
      "region": "西湖北岸",
      "status": "open",
      "targetType": "node",
      "scrollTarget": "duanqiao",
      "sourceStatus": "较可信",
      "summary": "从湖东桥路入北岸，进入断桥一带的长卷观察。",
      "position": {
        "x": 0.82,
        "y": 0.58
      }
    },
    {
      "id": "map-gushan",
      "label": "孤山路入口",
      "region": "西湖北岸",
      "status": "open",
      "targetType": "node",
      "scrollTarget": "sisheng-yanxiang-guan",
      "sourceStatus": "待考证",
      "summary": "沿北岸山水过渡，进入孤山路和近岸建筑段。",
      "position": {
        "x": 0.42,
        "y": 0.23
      }
    },
    {
      "id": "map-baoshu",
      "label": "保叔塔入口",
      "region": "西湖北岸",
      "status": "open",
      "targetType": "node",
      "scrollTarget": "baoshu-ta-chongshou-yuan",
      "sourceStatus": "较可信",
      "summary": "以北山塔影为锚点，进入寺观和山麓段。",
      "position": {
        "x": 0.55,
        "y": 0.18
      }
    },
    {
      "id": "map-xicun",
      "label": "西村渡口入口",
      "region": "西湖北岸",
      "status": "open",
      "targetType": "node",
      "scrollTarget": "xicun-dukou",
      "sourceStatus": "待考证",
      "summary": "从西村水岸进入市井、舟渡和湖岸收束段。",
      "position": {
        "x": 0.17,
        "y": 0.52
      }
    },
    {
      "id": "map-south-bank",
      "label": "南岸待展开",
      "region": "西湖南岸",
      "status": "locked",
      "targetType": "region",
      "scrollTarget": "future-south-bank",
      "sourceStatus": "创作性推演",
      "summary": "当前 MVP 聚焦北岸，全湖其他段后续接入。",
      "position": {
        "x": 0.43,
        "y": 0.84
      }
    },
    {
      "id": "map-city",
      "label": "城郭线索",
      "region": "湖东城郭",
      "status": "pending",
      "targetType": "region",
      "scrollTarget": "future-city-edge",
      "sourceStatus": "待考证",
      "summary": "作为后续校准城市与湖岸关系的线索点。",
      "position": {
        "x": 0.9,
        "y": 0.36
      }
    }
  ],
  "notes": [
    {
      "id": "note-entry-map",
      "category": "画作概览",
      "title": "从卷首到鸟瞰入口",
      "status": "创作性解读",
      "relatedNode": "duanqiao",
      "summary": "Landing 与入画的关系被处理为从题名、卷首到全湖示意图的空间转换，帮助用户先建立观看仪式和方位感。",
      "source": "项目设计说明，待补外部史料。"
    },
    {
      "id": "note-north-bank",
      "category": "图像线索",
      "title": "西湖北岸十五处细节点",
      "status": "待考证",
      "relatedNode": "gushan-road",
      "summary": "十五个节点来自当前 MVP 已确认清单，页面只使用节点名、图像位置和证据状态，不扩写未核实史实。",
      "source": "PRD v0.6 节点清单。"
    },
    {
      "id": "note-baoshu",
      "category": "图像线索",
      "title": "塔影与山麓寺院",
      "status": "较可信",
      "relatedNode": "baoshu-ta-chongshou-yuan",
      "summary": "保叔塔与崇寿院适合作为北岸空间识别锚点，后续需补充出处、年代和画中位置依据。",
      "source": "标注图与节点清单，待补文献。"
    },
    {
      "id": "note-uncertain",
      "category": "未定问题",
      "title": "园林名称和沿革待核验",
      "status": "待考证",
      "relatedNode": "houleyuan-jifang-yuyuan",
      "summary": "后乐园、集芳御园等名称涉及沿革与时段差异，首版在问湖中开放线索征集。",
      "source": "待补来源。"
    },
    {
      "id": "note-soundscape",
      "category": "方法论",
      "title": "随动声景的占位层",
      "status": "创作性解读",
      "relatedNode": "xicun-jiulou",
      "summary": "MVP 先以水岸、市井、寺钟三类占位声层验证交互逻辑，正式音频需另行授权。",
      "source": "TDD v0.4 声景策略。"
    }
  ],
  "inquiries": [
    {
      "id": "inq-001",
      "type": "question",
      "title": "后乐园与集芳御园的名称关系如何处理？",
      "status": "待核验",
      "related": "后乐园（原集芳御园）",
      "content": "希望补充名称沿革、时间段和可引用出处，避免页面直接写成定论。"
    },
    {
      "id": "inq-002",
      "type": "clue",
      "title": "保叔塔周边寺院线索需要来源",
      "status": "待核验",
      "related": "保叔塔与崇寿院",
      "content": "可优先检索地方志、图录和相关论文，确认画中寺院组合的表述口径。"
    },
    {
      "id": "inq-003",
      "type": "task",
      "title": "录入鸟瞰图可见入口点",
      "status": "待核验",
      "related": "入画地图",
      "content": "依据标注版本鸟瞰图，只录入适合全局入口的点，不强制覆盖十五个游湖节点。"
    }
  ]
};
})();
