import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  assetsManifestSchema,
  buildAppContent,
  coldKnowledgeSectionsSchema,
  inquiriesSchema,
  mapPointsSchema,
  notesSchema,
  scrollNodesSchema,
  scrollSegmentsSchema,
  siteSchema,
} from "../packages/schemas/src";

const isCheck = process.argv.includes("--check");

function readJson(path: string) {
  return JSON.parse(readFileSync(resolve(path), "utf8").replace(/^\uFEFF/, ""));
}

const appContent = buildAppContent({
  assets: assetsManifestSchema.parse(readJson("content/assets-manifest.json")),
  coldKnowledgeSections: coldKnowledgeSectionsSchema.parse(readJson("content/cold-knowledge.json")),
  inquiries: inquiriesSchema.parse(readJson("content/inquiries.json")),
  mapPoints: mapPointsSchema.parse(readJson("content/map-points.json")),
  notes: notesSchema.parse(readJson("content/notes.json")),
  scrollNodes: scrollNodesSchema.parse(readJson("content/scroll-nodes.json")),
  scrollSegments: scrollSegmentsSchema.parse(readJson("content/scroll-segments.json")),
  siteNavigation: siteSchema.parse(readJson("content/site.json")).navigation,
});

const output = `// Generated by tools/generate-app-content.ts. Do not edit by hand.
(function () {
  window.WEST_LAKE_CONTENT = ${JSON.stringify(appContent, null, 2)};
})();
`;

const outputPath = resolve("app/content-data.js");

if (isCheck) {
  const current = readFileSync(outputPath, "utf8");
  if (current !== output) {
    throw new Error("app/content-data.js is out of date. Run npm run generate:app-content.");
  }
  console.log("app content ok: app/content-data.js is up to date");
} else {
  try {
    const current = readFileSync(outputPath, "utf8");
    if (current === output) {
      console.log("app content ok: app/content-data.js is up to date");
      process.exit(0);
    }
  } catch {
    // The file will be created below when the filesystem permits it.
  }

  writeFileSync(outputPath, output, "utf8");
  console.log(`generated app/content-data.js with ${appContent.scrollSegments.length} scroll segments`);
}
